# Generated by Django 4.0.4 on 2022-04-21 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_alter_company_company_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_position', models.CharField(max_length=45)),
                ('job_description', models.TextField(default='')),
                ('hourly_salary', models.FloatField(blank=True, null=True)),
                ('years_of_experience_required', models.IntegerField(blank=True, null=True)),
                ('certification_required', models.CharField(choices=[('', ''), ('MIDDLE_SCHOOL', 'Middle School Diploma'), ('HIGH_SCHOOL', 'High School Diploma'), ('TRADE_SCHOOL', 'Vocational or Trade School Diploma'), ('OTHER', 'Other')], default='', max_length=100)),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
