# Generated by Django 4.0.4 on 2022-04-14 20:02

import django.core.serializers.json
from django.db import migrations, models
import json.decoder


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='certifications',
            field=models.JSONField(decoder=json.decoder.JSONDecoder, default={'certification_name': '', 'date_of_completion': '', 'institution': ''}, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddField(
            model_name='candidate',
            name='city_of_residence',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='candidate',
            name='country',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='candidate',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='first_names',
            field=models.CharField(default='', max_length=65),
        ),
        migrations.AddField(
            model_name='candidate',
            name='last_name',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='candidate',
            name='password',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='candidate',
            name='state_province',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='candidate',
            name='username',
            field=models.CharField(default='', max_length=45, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='work_experience',
            field=models.JSONField(decoder=json.decoder.JSONDecoder, default={'company': '', 'end_date': '', 'position': '', 'start_date': ''}, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
