# Generated by Django 4.0.4 on 2022-04-15 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_candidate_certifications_candidate_city_of_residence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_category', models.CharField(choices=[('CV', 'CV'), ('COVER_LETTER', 'Cover letter')], default='CV', max_length=25)),
                ('file', models.FileField(upload_to='media/uploads/')),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidate.candidate')),
            ],
        ),
    ]
