# Generated by Django 4.0.4 on 2022-04-16 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_remove_candidate_email_remove_candidate_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvupload',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate'),
        ),
    ]
