# Generated by Django 4.0.4 on 2022-04-20 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_alter_cvupload_candidate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cvupload',
            old_name='candidate',
            new_name='user',
        ),
    ]
