# Generated by Django 4.0.4 on 2022-04-21 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_rename_candidate_cvupload_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cvupload',
            old_name='user',
            new_name='user_id',
        ),
    ]
