# Generated by Django 4.0.4 on 2022-04-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_email', models.EmailField(default='', max_length=254, unique=True)),
                ('password', models.CharField(default='', max_length=64)),
                ('company_summary', models.TextField(default='')),
                ('company_address', models.CharField(max_length=100)),
            ],
        ),
    ]
